# Generated by Django 4.1.7 on 2023-02-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skills_skill_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill_image',
        ),
    ]
