# Generated by Django 4.1.7 on 2023-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(default=None, upload_to='files/images/projects'),
        ),
    ]
